.. list-table:: ADC Function
   :name: tab-adc-gpio
   :header-rows: 1
   :widths: 50 50
   :align: center

   * - GPIO Pin Name
     - ADC Function
   * - SENSOR_VP
     - ADC1_CH0
   * - SENSOR_CAPP
     - ADC1_CH1
   * - SENSOR_CAPN
     - ADC1_CH2
   * - SENSOR_VN
     - ADC1_CH3
   * - 32K_XP
     - ADC1_CH4
   * - 32K_XN
     - ADC1_CH5
   * - VDET_1
     - ADC1_CH6
   * - VDET_2
     - ADC1_CH7
   * - GPIO4
     - ADC2_CH0
   * - GPIO0
     - ADC2_CH1
   * - GPIO2
     - ADC2_CH2
   * - MTDO
     - ADC2_CH3
   * - MTCK
     - ADC2_CH4
   * - MTDI
     - ADC2_CH5
   * - MTMS
     - ADC2_CH6
   * - GPIO27
     - ADC2_CH7
   * - GPIO25
     - ADC2_CH8
   * - GPIO26
     - ADC2_CH9
