The proper size and shape of an electrode improves system sensitivity. Round, oval, or shapes similar to a human fingertip are commonly applied. Large size or irregular shape might lead to incorrect responses from nearby electrodes.

Figure :ref:`fig-touch-electrode` shows the proper and improper size or shape of electrode. Please note that the examples illustrated in the figure are not of actual scale. It is suggested to use a human fingertip as reference.

.. figure:: ../_static/shared-touch-electrode.png
    :name: fig-touch-electrode
    :align: center
    :width: 50%
    :alt: {IDF_TARGET_NAME} Electrode Pattern Requirements

    {IDF_TARGET_NAME} Electrode Pattern Requirements