.. list-table:: Touch Sensor Functions
   :name: tab-touch-gpio
   :header-rows: 1
   :widths: 50 50
   :align: center

   * - GPIO Pin Name
     - Touch Sensor Function
   * - GPIO4
     - TOUCH00
   * - GPIO0
     - TOUCH1
   * - GPIO2
     - TOUCH2
   * - MTDO
     - TOUCH3
   * - MTCK
     - TOUCH4
   * - MTDI
     - TOUCH5
   * - MTMS
     - TOUCH6
   * - GPIO27
     - TOUCH7
   * - 32K_XN
     - TOUCH8
   * - 32K_XP
     - TOUCH9
