In a two-layer PCB design, the RF trace is routed as shown highlighted in pink in Figure :ref:`fig-rf-layout-two-layer`. The width of the RF trace should be greater than that of the RF trace in a four-layer board and is normally over 20 mil. The actual width depends on the impedance formula where impedance-relevant parameters may vary depending on the number of PCB layers.

Other good practices for routing RF traces in four-layer PCB designs still apply to two-layer board designs.

.. figure:: ../_static/{IDF_TARGET_PATH_NAME}/{IDF_TARGET_PATH_NAME}-pcb-rf-layout-two-layer.png
    :name: fig-rf-layout-two-layer
    :align: center
    :width: 70%
    :alt: {IDF_TARGET_NAME} RF Layout in a Two-layer PCB Design

    {IDF_TARGET_NAME} RF Layout in a Two-layer PCB Design