.. list-table:: Revision History
   :header-rows: 1
   :widths: 2 1 7

   * - Date
     - Version
     - Release Notes
   * - 2025-09-17
     - v1.9
     -  - :doc:`../pcb-layout-design`
            - Added Figure :ref:`fig-module-place-on-base-board-left`
            - Updated Figure :ref:`fig-module-place-on-base-board-right`
   * - 2025-07-23
     - v1.8
     - Improved wording throughout the document
   * - 2025-05-23
     - v1.7
     -  - :doc:`../pcb-layout-design`
            - Section :ref:`sdio-layout`: Updated descriptions about the SDIO layout guidelines
            - Section :ref:`crystal-layout`: Updated descriptions about the crystal layout guidelines
   * - 2024-12-27
     - v1.6
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-rtc-clock-source`: Updated descriptions about the 32.768 crystal and chip revisions
   * - 2024-12-09
     - v1.5
     -  - :ref:`hardware-development-modules`：
            - Added download links to module reference designs
   * - 2024-11-15
     - v1.4
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-spi`: Newly added section
   * - 2024-10-15
     - v1.3
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-ethernet-mac`: Newly added section
            - Section :ref:`schematic-checklist-uart`: Updated the AT related description
   * - 2024-01-09
     - v1.2
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-rf-tunning`: Updated RF matching description
   * - 2023-12-25
     - v1.1
     -  - :doc:`../pcb-layout-design`
            - Section :ref:`crystal-layout`: Updated crystal PCB layout
   * - 2023-12-22
     - v1.0
     - Migrated {IDF_TARGET_NAME} Hardware Design Guidelines from PDF to HTML format. During the migration from PDF to HTML format, minor updates, improvements, and clarifications were made throughout the documentation. If you would like to check previous versions of the document, please submit documentation feedback.
