Figure :ref:`fig-touch-sensor-routing` illustrates the general guidelines to routing traces. Specifically,

- The trace should be as short as possible and no longer than 300 mm.
- The trace width (W) can not be larger than 0.18 mm (7 mil).
- The alignment angle (R) should not be less than 90°.
- The trace-to-ground gap (S) should be in the range of 0.5 mm to 1 mm.
- The electrode diameter (D) should be in the range of 8 mm to 15 mm.
- Hatched ground should be added around the electrodes and traces.
- The traces should be isolated well and routed away from that of the antenna.

.. figure:: ../_static/shared-touch-sensor-routing.png
    :name: fig-touch-sensor-routing
    :align: center
    :width: 70%
    :alt: {IDF_TARGET_NAME} Sensor Track Routing Requirements

    {IDF_TARGET_NAME} Sensor Track Routing Requirements
