.. list-table:: Pin Mapping Between Chip and Off-Package Flash
    :name: tab-chip-flash-pin-mapping
    :header-rows: 1
    :widths: 15 20 20 20 25
    :align: center

    * - Pin No.
      - Pin Name
      - Single SPI
      - Dual SPI
      - Quad SPI/QPI
    * - 36
      - SPICS
      - CS#
      - CS#
      - CS#
    * - 37
      - SPIQ
      - DO
      - DO
      - DO
    * - 38
      - SPIWP
      - WP#
      - WP#
      - WP#
    * - 40
      - SPIHD
      - HOLD#
      - HOLD#
      - HOLD#
    * - 41
      - SPICLK
      - CLK
      - CLK
      - CLK
    * - 42
      - SPID
      - DI
      - DI
      - DI
