.. list-table:: ADC Functions
   :name: tab-adc-gpio
   :header-rows: 1
   :widths: 50 50
   :align: center

   * - GPIO Pin
     - ADC Function
   * - GPIO42
     - ADC1_CH0_N
   * - GPIO43
     - ADC1_CH0_P
   * - GPIO44
     - ADC1_CH1_N
   * - GPIO45
     - ADC1_CH1_P
   * - GPIO46
     - ADC1_CH2_N
   * - GPIO47
     - ADC1_CH2_P
   * - GPIO48
     - ADC1_CH3_N
   * - GPIO49
     - ADC1_CH3_P
   * - GPIO50
     - ADC2_CH0_N
   * - GPIO51
     - ADC2_CH0_P
   * - GPIO52
     - ADC2_CH1_N
   * - GPIO53
     - ADC2_CH1_P
   * - MTDO/GPIO54
     - ADC2_CH2_N
   * - MTCK/GPIO55
     - ADC2_CH2_P
   * - MTDI/GPIO56
     - ADC2_CH3_N
   * - MTMS/GPIO57
     - ADC2_CH3_P
