.. list-table:: Revision History
   :header-rows: 1
   :widths: 2 1 7

   * - Date
     - Version
     - Release Notes
   * - 2026-08-31
     - v0.2
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-power-supply`: Updated the recommended output current and Figure :ref:`fig-chip-power-scheme`
        - :doc:`../related-documentation-and-resources`: Added the reference designs for ESP32-S31-WROOM-3-N8R16V, ESP32-S31-Function-CoreBoard-1, and ESP32-S31-Korvo-1
   * - 2026-06-23
     - v0.1
     - First release
