.. list-table:: Revision History
   :header-rows: 1
   :widths: 2 1 7

   * - Date
     - Version
     - Release Notes
   * - 2025-06-05
     - v1.6
     -  - :doc:`../pcb-layout-design`
            - Section :ref:`usb-layout`: Updated descriptions about the USB layout guidelines
   * - 2025-05-23
     - v1.5
     -  - :doc:`../pcb-layout-design`
            - Section :ref:`crystal-layout`: Updated descriptions about the crystal layout guidelines
   * - 2024-11-15
     - v1.4
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-spi`: Newly added section
   * - 2024-10-15
     - v1.3
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-uart`: Updated the AT related description
   * - 2024-01-09
     - v1.2
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-rf-tunning`: Updated RF matching description
   * - 2023-12-25
     - v1.1
     -  - :doc:`../pcb-layout-design`
            - Section :ref:`crystal-layout`: Updated crystal PCB layout
   * - 2023-12-22
     - v1.0
     - Migrated {IDF_TARGET_NAME} Hardware Design Guidelines from PDF to HTML format. During the migration from PDF to HTML format, minor updates, improvements, and clarifications were made throughout the documentation. If you would like to check previous versions of the document, please submit documentation feedback.
