# The content below is copied from the esp-docs repo and modified acc to zh_CN language

# -*- coding: utf-8 -*-
#
# English Language RTD & Sphinx config file
#
# Uses ../conf_common.py for most non-language-specific settings.

# Importing conf_common adds all the non-language-specific
# parts to this conf module

try:
    from conf_common import *  # noqa: F403,F401
except ImportError:
    import os
    import sys
    sys.path.insert(0, os.path.abspath('../'))
    from conf_common import *  # noqa: F403,F401

import datetime

current_year = datetime.datetime.now().year

# General information about the project.
project = u'ESP 硬件设计指南'
copyright = u'2023 - {}, 乐鑫信息科技（上海）股份有限公司'.format(current_year)
pdf_title = u'硬件设计指南'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'zh_CN'

doc_id = {'esp32': '4090', 'esp32s2': '4421', 'esp32s3': '5420', 'esp32c2': '5725', 'esp32c3': '5085', 'esp32c6': '6513', 'esp32h2': '6717', 'esp32c5': '8821', 'esp32p4': '8879', 'esp32c61': '9577'}

html_js_files = ['js/chatbot_widget_cn.js']
