.. list-table:: Revision History
   :header-rows: 1
   :widths: 2 1 7

   * - Date
     - Version
     - Release Notes
   * - 2025-12-09
     - v1.4
     - :doc:`../related-documentation-and-resources`: Added Section :ref:`hardware-development-modules`
   * - 2025-09-02
     - v1.3
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-overview`: Updated Figure :ref:`fig-chip-core-schematic`
            - Section :ref:`schematic-checklist-power-supply`: Updated the output current; added the description of analog power supply capacitors
            - Section :ref:`schematic-checklist-flash-psram`: Updated Figure :ref:`fig-external-flash-psram-schematic`
            - Section :ref:`schematic-checklist-rf-circuit`: Added the CLCCL matching circuit description
            - Section :ref:`schematic-checklist-rf-tunning`: Updated the description of S21 frequency
            - Section :ref:`schematic-checklist-uart`: Updated the signal-related description and the capacitor-related note
        - :doc:`../pcb-layout-design`
            - Section :ref:`pcb-layout-design-power-supply`: Updated the width of main power trace and the capacitor-related description
            - Section :ref:`rf-layout`: Updated the CLC matching circuit description
   * - 2025-06-05
     - v1.2
     -  - :doc:`../pcb-layout-design`
            - Section :ref:`usb-layout`: Updated descriptions about the USB layout guidelines
   * - 2025-05-23
     - v1.1
     -  - :doc:`../pcb-layout-design`
            - Section :ref:`sdio-layout`: Updated descriptions about the SDIO layout guidelines
            - Section :ref:`crystal-layout`: Updated descriptions about the crystal layout guidelines
   * - 2025-3-31
     - v1.0
     - First release of {IDF_TARGET_NAME} Hardware Design Guidelines.
