.. list-table:: 芯片上电过程中的管脚毛刺
   :name: tab-glitches-on-pins
   :header-rows: 1
   :widths: 30 50 20
   :align: center

   * - 管脚名称
     - 毛刺类型 [#]_
     - 典型持续时间 (ns)
   * - MTCK
     - 低电平毛刺
     - 5
   * - MTDO
     - 低电平毛刺
     - 5
   * - GPIO10
     - 低电平毛刺
     - 5
   * - U0RXD
     - 低电平毛刺
     - 5
   * - GPIO18
     - 高电平毛刺
     - 50,000



.. [#]

    - 低电平毛刺：管脚在持续期间维持低电平输出状态
    - 高电平毛刺：管脚在持续期间维持高电平输出状态
