.. list-table:: Power-Up Glitches on Pins
   :name: tab-glitches-on-pins
   :header-rows: 1
   :widths: 30 50 20
   :align: center

   * - Pin
     - Glitch [#]_
     - Typical Time (ns)
   * - MTCK
     - Low-level glitch
     - 5
   * - MTDO
     - Low-level glitch
     - 5
   * - GPIO10
     - Low-level glitch
     - 5
   * - U0RXD
     - Low-level glitch
     - 5
   * - GPIO18
     - High-level glitch
     - 50,000



.. [#]

    - Low-level glitch: the pin is at a low level output status during the time period;
    - High-level glitch: the pin is at a high level output status during the time period.
