.. list-table:: 修订历史
   :header-rows: 1
   :widths: 2 1 7

   * - 日期
     - 版本
     - 发布说明
   * - 2026-08-31
     - v0.2
     -  - :doc:`../schematic-checklist`
            - 章节 :ref:`schematic-checklist-power-supply`：更新最大输出电流及图 :ref:`fig-chip-power-scheme`
        - :doc:`../related-documentation-and-resources`：新增 ESP32-S31-WROOM-3-N8R16V、ESP32-S31-Function-CoreBoard-1 和 ESP32-S31-Korvo-1 参考设计
   * - 2026-06-23
     - v0.1
     - 首次发布
