.. list-table:: 触摸传感器功能
   :name: tab-touch-gpio
   :header-rows: 1
   :widths: 50 50
   :align: center

   * - GPIO 管脚
     - 触摸传感器功能
   * - GPIO6
     - TOUCH_CH0
   * - GPIO7
     - TOUCH_CH1
   * - GPIO8
     - TOUCH_CH2
   * - GPIO9
     - TOUCH_CH3
   * - GPIO10
     - TOUCH_CH4
   * - GPIO11
     - TOUCH_CH5
   * - GPIO12
     - TOUCH_CH6
   * - GPIO13
     - TOUCH_CH7
   * - GPIO14
     - TOUCH_CH8
   * - GPIO15
     - TOUCH_CH9
   * - GPIO16
     - TOUCH_CH10
   * - GPIO17
     - TOUCH_CH11
   * - GPIO18
     - TOUCH_CH12
   * - GPIO19
     - TOUCH_CH13
