.. list-table:: Touch Sensor Functions
   :name: tab-touch-gpio
   :header-rows: 1
   :widths: 50 50
   :align: center

   * - GPIO Pin Name
     - Touch Sensor Function
   * - GPIO1
     - TOUCH1
   * - GPIO2
     - TOUCH2
   * - GPIO3
     - TOUCH3
   * - GPIO4
     - TOUCH4
   * - GPIO5
     - TOUCH5
   * - GPIO6
     - TOUCH6
   * - GPIO7
     - TOUCH7
   * - GPIO8
     - TOUCH8
   * - GPIO9
     - TOUCH9
   * - GPIO10
     - TOUCH10
   * - GPIO11
     - TOUCH11
   * - GPIO12
     - TOUCH12
   * - GPIO13
     - TOUCH13
   * - GPIO14
     - TOUCH14
