.. list-table:: Revision History
   :header-rows: 1
   :widths: 2 1 7

   * - Date
     - Version
     - Release Notes
   * - 2025-07-03
     - v1.8
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-overview`: Updated Figure :ref:`fig-chip-core-schematic`
            - Section :ref:`schematic-checklist-power-supply`: Added Figure :ref:`fig-chip-power-scheme`; deleted Figure *{IDF_TARGET_NAME} Schematic for Digital Power Supply Pins* and the *RTC Power Supply* section; updated descriptions
            - Section :ref:`schematic-checklist-external-crystal-source`: Updated Figure :ref:`fig-external-crystal-schematic`
            - Section :ref:`schematic-checklist-rf-tunning`: Updated descriptions
            - Section :ref:`schematic-checklist-uart`: Updated descriptions
            - Section :ref:`schematic-checklist-strapping-pins`: Updated descriptions
            - Section :ref:`schematic-checklist-gpio`: Simplified Table :ref:`IO MUX Pin Functions`
            - Section :ref:`schematic-checklist-adc`: Added Table :ref:`tab-adc-gpio`
            - Section :ref:`schematic-checklist-usb`: Added Figure :ref:`fig-usb-rc-schematic`
            - Section :ref:`schematic-checklist-touch`: Added Table :ref:`tab-touch-gpio`; updated descriptions
        - :doc:`../pcb-layout-design`
            - Section :ref:`pcb-layout-design-power-supply`: Restructured the section and updated descriptions
            - Section :ref:`rf-layout`: Updated Figure :ref:`fig-stackup-design`; added Figure :ref:`fig-pcb-ipex-layout`; updated descriptions
            - Section :ref:`schematic-checklist-rf-circuit`: Updated Figure :ref:`fig-rf-matching-schematic`
   * - 2025-06-05
     - v1.7
     -  - :doc:`../pcb-layout-design`
            - Section :ref:`usb-layout`: Updated descriptions about the USB layout guidelines
   * - 2025-05-23
     - v1.6
     -  - :doc:`../pcb-layout-design`
            - Section :ref:`sdio-layout`: Updated descriptions about the SDIO layout guidelines
            - Section :ref:`crystal-layout`: Updated descriptions about the crystal layout guidelines
   * - 2025-04-02
     - v1.5
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-strapping-pins`: Updated Table :ref:`tab-chip-boot-mode-control`
   * - 2025-01-07
     - v1.4
     -  - :ref:`hardware-development-modules`：
            - Added download links to module reference designs
   * - 2024-11-15
     - v1.3
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-spi`: Newly added section
   * - 2024-01-09
     - v1.2
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-rf-tunning`: Updated RF matching description
   * - 2023-12-25
     - v1.1
     -  - :doc:`../pcb-layout-design`
            - Section :ref:`crystal-layout`: Updated crystal PCB layout
   * - 2023-12-22
     - v1.0
     - Migrated {IDF_TARGET_NAME} Hardware Design Guidelines from PDF to HTML format. During the migration from PDF to HTML format, minor updates, improvements, and clarifications were made throughout the documentation. If you would like to check previous versions of the document, please submit documentation feedback.
