.. list-table:: 芯片与封装内 Flash 的管脚对应关系
    :name: tab-chip-flash-pin-mapping
    :header-rows: 1
    :widths: 50 50
    :align: center

    * - ESP32-U4WDH
      - 封装内 Flash (4 MB)
    * - SD_DATA_1
      - IO0/DI
    * - GPIO17
      - IO1/DO
    * - SD_DATA_0
      - IO2/WP#
    * - SD_CMD
      - IO3/HOLD#
    * - SD_CLK
      - CLK
    * - GPIO16
      - CS#
    * - GND
      - VSS
    * - VDD_SDIO
      - VDD

.. list-table:: 芯片与封装内 PSRAM 的管脚对应关系
    :name: tab-chip-psram-pin-mapping
    :header-rows: 1
    :widths: 50 50
    :align: center

    * - ESP32-D0WDR2-V3
      - 封装内 PSRAM (2 MB)
    * - SD_DATA_1
      - SIO0/SI
    * - SD_DATA_0
      - SIO1/SO
    * - SD_DATA_3
      - SIO2
    * - SD_DATA_2
      - SIO3
    * - SD_CLK
      - SCLK
    * - GPIO16
      - CE#
    * - GND
      - VSS
    * - VDD_SDIO
      - VDD





