.. list-table:: 修订历史
   :header-rows: 1
   :widths: 2 1 7

   * - 日期
     - 版本
     - 发布说明
   * - 2025-09-17
     - v1.9
     - 更新图片 :ref:`fig-module-place-on-base-board-left` 和 :ref:`fig-module-place-on-base-board-right`
   * - 2025-07-23
     - v1.8
     - 优化全文措辞
   * - 2025-05-23
     - v1.7
     -  - :doc:`../pcb-layout-design`
            - 章节 :ref:`sdio-layout`：更新 SDIO 版图设计规范
            - 章节 :ref:`crystal-layout`：更新晶振版图设计规范
   * - 2024-12-27
     - v1.6
     -  - :doc:`../schematic-checklist`
            - 章节 :ref:`schematic-rtc-clock-source`：更新关于 32.768 晶振与芯片版本的说明
   * - 2024-12-09
     - v1.5
     -  - :ref:`hardware-development-modules`：
            - 增加模组参考设计的下载链接
   * - 2024-11-15
     - v1.4
     -  - :doc:`../schematic-checklist`
            - 章节 :ref:`schematic-checklist-spi`：新增章节
   * - 2024-10-15
     - v1.3
     -  - :doc:`../schematic-checklist`
            - 章节 :ref:`schematic-checklist-ethernet-mac`：新增章节
            - 章节 :ref:`schematic-checklist-uart`：更新 AT 相关的描述
   * - 2024-01-09
     - v1.2
     -  - :doc:`../schematic-checklist`
            - 章节 :ref:`schematic-checklist-rf-tunning`：更新 RF 匹配电路相关的描述
   * - 2023-12-25
     - v1.1
     -  - :doc:`../pcb-layout-design`
            - 章节 :ref:`crystal-layout`：更新晶振 PCB 布局
   * - 2023-12-22
     - v1.0
     - 首次发布《{IDF_TARGET_NAME} 硬件设计指南》 HTML 版本。在从 PDF 转换为 HTML 格式的过程中，我们对文档进行了一些微小的修改和润色。如果您需要查看历史版本，请提交文档反馈。
