图 :ref:`fig-touch-sensor-routing` 为传感器布线布局，具体的走线注意事项如下：

- 走线长度请尽量短，建议不超过 300 mm。
- 走线宽度 (W) 不能大于 0.18 mm (7 mil)。
- 走线夹角 (R) 不应小于 90°。
- 走线离地间隙 (S) 范围 0.5 mm 到 1 mm。
- 触摸电极直径 (D) 范围 8 mm 到 15 mm。
- 触摸电极和走线应被栅格地围绕。
- 触摸传感器电路注意远离射频天线电路，并注意隔离。

.. figure:: ../_static/shared-touch-sensor-routing.png
    :name: fig-touch-sensor-routing
    :align: center
    :width: 70%
    :alt: {IDF_TARGET_NAME} 传感器布局布线

    {IDF_TARGET_NAME} 传感器布局布线
