.. list-table:: 修订历史
   :header-rows: 1
   :widths: 2 1 7

   * - 日期
     - 版本
     - 发布说明
   * - 2025-07-03
     - v1.8
     -  - :doc:`../schematic-checklist`
            - 章节 :ref:`schematic-checklist-overview`：更新 :ref:`fig-chip-core-schematic`
            - 章节 :ref:`schematic-checklist-power-supply`：新增图 :ref:`fig-chip-power-scheme`；删除 *{IDF_TARGET_NAME} 系列芯片数字电源电路图* 和 *RTC 电源* 小节；更新描述
            - 章节 :ref:`schematic-checklist-external-crystal-source`：更新图 :ref:`fig-external-crystal-schematic`
            - 章节 :ref:`schematic-checklist-rf-tunning`：更新描述
            - 章节 :ref:`schematic-checklist-uart`：更新描述
            - 章节 :ref:`schematic-checklist-strapping-pins`：更新描述
            - 章节 :ref:`schematic-checklist-gpio`：精简表格 :ref:`IO MUX Pin Functions`
            - 章节 :ref:`schematic-checklist-adc`：新增表格 :ref:`tab-adc-gpio`
            - 章节 :ref:`schematic-checklist-usb`：新增图 :ref:`fig-usb-rc-schematic`
            - 章节 :ref:`schematic-checklist-touch`：新增表格 :ref:`tab-touch-gpio` 并更新描述
        - :doc:`../pcb-layout-design`
            - 章节 :ref:`pcb-layout-design-power-supply`：更新小节结构与描述
            - 章节 :ref:`rf-layout`：更新图 :ref:`fig-stackup-design`；新增图 :ref:`fig-pcb-ipex-layout`；更新描述
            - 章节 :ref:`schematic-checklist-rf-circuit`：更新图 :ref:`fig-rf-matching-schematic`
   * - 2025-06-05
     - v1.7
     -  - :doc:`../pcb-layout-design`
            - 章节 :ref:`usb-layout`：更新 USB 版图设计规范
   * - 2025-05-23
     - v1.6
     -  - :doc:`../pcb-layout-design`
            - 章节 :ref:`sdio-layout`：更新 SDIO 版图设计规范
            - 章节 :ref:`crystal-layout`：更新晶振版图设计规范
   * - 2025-04-02
     - v1.5
     -  - :doc:`../schematic-checklist`
            - 章节 :ref:`schematic-checklist-strapping-pins`: 更新表格 :ref:`tab-chip-boot-mode-control`
   * - 2025-01-07
     - v1.4
     -  - :ref:`hardware-development-modules`：
            - 增加模组参考设计的下载链接
   * - 2024-11-15
     - v1.3
     -  - :doc:`../schematic-checklist`
            - 章节 :ref:`schematic-checklist-spi`：新增章节
   * - 2024-01-09
     - v1.2
     -  - :doc:`../schematic-checklist`
            - 章节 :ref:`schematic-checklist-rf-tunning`：更新 RF 匹配电路相关的描述
   * - 2023-12-25
     - v1.1
     -  - :doc:`../pcb-layout-design`
            - 章节 :ref:`crystal-layout`：更新晶振 PCB 布局
   * - 2023-12-22
     - v1.0
     - 首次发布《{IDF_TARGET_NAME} 硬件设计指南》 HTML 版本。在从 PDF 转换为 HTML 格式的过程中，我们对文档进行了一些微小的修改和润色。如果您需要查看历史版本，请提交文档反馈。
