.. list-table:: ADC 功能
   :name: tab-adc-gpio
   :header-rows: 1
   :widths: 50 50
   :align: center

   * - GPIO 管脚
     - ADC 功能
   * - GPIO1
     - ADC1_CH0
   * - GPIO2
     - ADC1_CH1
   * - GPIO3
     - ADC1_CH2
   * - GPIO4
     - ADC1_CH3
   * - GPIO5
     - ADC1_CH4
   * - GPIO6
     - ADC1_CH5
   * - GPIO7
     - ADC1_CH6
   * - GPIO8
     - ADC1_CH7
   * - GPIO9
     - ADC1_CH8
   * - GPIO10
     - ADC1_CH9
   * - GPIO11
     - ADC2_CH0
   * - GPIO12
     - ADC2_CH1
   * - GPIO13
     - ADC2_CH2
   * - GPIO14
     - ADC2_CH3
   * - GPIO15
     - ADC2_CH4
   * - GPIO16
     - ADC2_CH5
   * - GPIO17
     - ADC2_CH6
   * - GPIO18
     - ADC2_CH7
   * - GPIO19
     - ADC2_CH8
   * - GPIO20
     - ADC2_CH9
