使用 ADC 功能时，请靠近管脚添加 0.1 μF 的对地滤波电容，精度会更准确一些。

.. list-table::
    :header-rows: 1
    :widths: 15 10

    * - ADC 通道信号
      - 管脚名称

    * - ADC1_CHANNEL0
      - GPIO16
    * - ADC1_CHANNEL1
      - GPIO17
    * - ADC1_CHANNEL2
      - GPIO18
    * - ADC1_CHANNEL3
      - GPIO19
    * - ADC1_CHANNEL4
      - GPIO20
    * - ADC1_CHANNEL5
      - GPIO21
    * - ADC1_CHANNEL6
      - GPIO22
    * - ADC1_CHANNEL7
      - GPIO23
    * - ADC2_CHANNEL0
      - GPIO49
    * - ADC2_CHANNEL1
      - GPIO50
    * - ADC2_CHANNEL2
      - GPIO51
    * - ADC2_CHANNEL3
      - GPIO52
    * - ADC2_CHANNEL4
      - GPIO53
    * - ADC2_CHANNEL5
      - GPIO54
