.. _IO MUX Pin Functions:

.. csv-table:: IO 默认管脚配置
    :header-rows: 1

    管脚序号,管脚名称,供电管脚,复位时,复位后
    1,GPIO1,VDD_LP/VDD_BAT,--,--
    2,GPIO2,VDD_LP/VDD_BAT,--,"IE, WPU"
    3,GPIO3,VDD_LP/VDD_BAT,--,IE
    4,GPIO4,VDD_LP,--,IE
    5,GPIO5,VDD_LP,--,--
    6,GPIO6,VDD_LP,--,--
    7,GPIO7,VDD_LP,--,--
    8,GPIO8,VDD_LP,--,--
    10,GPIO9,VDD_LP,--,--
    11,GPIO10,VDD_LP,--,--
    12,GPIO11,VDD_LP,--,--
    13,GPIO12,VDD_LP,--,--
    14,GPIO13,VDD_LP,--,--
    15,GPIO14,VDD_LP,--,--
    16,GPIO15,VDD_LP,--,--
    17,GPIO16,VDD_IO_0,--,--
    18,GPIO17,VDD_IO_0,--,--
    19,GPIO18,VDD_IO_0,--,--
    20,GPIO19,VDD_IO_0,--,--
    22,GPIO20,VDD_IO_0,--,--
    23,GPIO21,VDD_IO_0,--,--
    24,GPIO22,VDD_IO_0,--,--
    25,GPIO23,VDD_IO_0,--,--
    52,GPIO24,VDD_IO_4,--,--
    53,GPIO25,VDD_IO_4,--,"IE, USB_PU"
    55,GPIO26,VDD_IO_4,--,--
    56,GPIO27,VDD_IO_4,--,--
    57,GPIO28,VDD_IO_4,--,--
    58,GPIO29,VDD_IO_4,--,--
    60,GPIO30,VDD_IO_4,--,--
    61,GPIO31,VDD_IO_4,--,--
    63,GPIO32,VDD_IO_4,IE,--
    64,GPIO33,VDD_IO_4,IE,--
    65,GPIO34,VDD_IO_4,IE,--
    66,GPIO35,VDD_IO_4,"IE, WPU",--
    68,GPIO36,VDD_IO_4,IE,--
    69,GPIO37,VDD_IO_4,IE,--
    70,GPIO38,VDD_IO_4,IE,--
    80,GPIO39,VDD_IO_5,--,--
    81,GPIO40,VDD_IO_5,--,--
    82,GPIO41,VDD_IO_5,--,--
    83,GPIO42,VDD_IO_5,--,--
    84,GPIO43,VDD_IO_5,--,--
    86,GPIO44,VDD_IO_5,--,--
    87,GPIO45,VDD_IO_5,--,--
    88,GPIO46,VDD_IO_5,--,--
    89,GPIO47,VDD_IO_5,--,--
    90,GPIO48,VDD_IO_5,--,--
    92,GPIO49,VDD_IO_6,--,--
    93,GPIO50,VDD_IO_6,--,--
    94,GPIO51,VDD_IO_6,--,--
    95,GPIO52,VDD_IO_6,--,--
    97,GPIO53,VDD_IO_6,--,--
    98,GPIO54,VDD_IO_6,--,--
    104,GPIO0,VDD_LP/VDD_BAT,--,--
