.. _ADC Functions:

ADC functions are shown in the table below.

.. list-table:: ADC Functions
   :name: tab-adc-gpio
   :header-rows: 1
   :widths: 20 30 50

   * - 6
     - GPIO0
     - ADC1_CH0
   * - 7
     - GPIO1
     - ADC1_CH1
   * - 8
     - GPIO2
     - ADC1_CH2
   * - 9
     - GPIO3
     - ADC1_CH3
   * - 10
     - GPIO4
     - ADC1_CH4
   * - 11
     - GPIO5
     - ADC1_CH5
   * - 12
     - GPIO6
     - ADC1_CH6
