.. list-table:: Revision History
   :header-rows: 1
   :widths: 2 1 7

   * - Date
     - Version
     - Release Notes
   * - 2025-05-23
     - v1.7
     -  - :doc:`../pcb-layout-design`
            - Section :ref:`crystal-layout`: Updated descriptions about the crystal layout guidelines
   * - 2025-01-07
     - v1.6
     -  - :ref:`hardware-development-modules`：
            - Added download links to module reference designs
   * - 2024-11-15
     - v1.5
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-spi`: Newly added section
   * - 2024-10-15
     - v1.4
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-uart`: Updated the AT related description
   * - 2024-06-14
     - v1.3
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-overview`: Updated Figure :ref:`fig-chip-core-schematic`
   * - 2024-01-09
     - v1.2
     -  - :doc:`../schematic-checklist`
            - Section :ref:`schematic-checklist-rf-tunning`: Updated RF matching description
   * - 2023-12-25
     - v1.1
     -  - :doc:`../pcb-layout-design`
            - Section :ref:`crystal-layout`: Updated crystal PCB layout
   * - 2023-12-22
     - v1.0
     - Migrated {IDF_TARGET_NAME} Hardware Design Guidelines from PDF to HTML format. During the migration from PDF to HTML format, minor updates, improvements, and clarifications were made throughout the documentation. If you would like to check previous versions of the document, please submit documentation feedback.
