.. list-table:: Power-Up Glitches on Pins
   :name: tab-glitches-on-pins
   :header-rows: 1
   :widths: 30 50 20
   :align: center

   * - Pin
     - Glitch [#]_
     - Typical Time (µs)
   * - GPIO0
     - Low-level glitch
     - 40
   * - GPIO1
     - Low-level glitch
     - 60
   * - GPIO3
     - Low-level glitch
     - 60
   * - MTDI
     - Low-level glitch
     - 60



.. [#]

    Low-level glitch: the pin is at a low level output status during the time period;

