.. list-table:: 修订历史
   :header-rows: 1
   :widths: 2 1 7

   * - 日期
     - 版本
     - 发布说明
   * - 2025-09-02
     - v1.3
     -  - :doc:`../schematic-checklist`
            - 章节 :ref:`schematic-checklist-overview`：更新图 :ref:`fig-chip-core-schematic`
            - 章节 :ref:`schematic-checklist-power-supply`：更新最大输出电流，新增模拟电源电容描述
            - 章节 :ref:`schematic-checklist-flash-psram`：更新图 :ref:`fig-external-flash-psram-schematic`
            - 章节 :ref:`schematic-checklist-rf-circuit`：新增 CLCCL 匹配电路描述
            - 章节 :ref:`schematic-checklist-rf-tunning`：更新 S21 频率描述
            - 章节 :ref:`schematic-checklist-uart`：更新信号相关描述及电容相关注释
        - :doc:`../pcb-layout-design`
            - 章节 :ref:`pcb-layout-design-power-supply`：更新主干电源走线线宽及电容相关描述
            - 章节 :ref:`rf-layout`：更新 CLC 匹配电路描述
   * - 2025-06-05
     - v1.2
     -  - :doc:`../pcb-layout-design`
            - 章节 :ref:`usb-layout`：更新 USB 版图设计规范
   * - 2025-05-23
     - v1.1
     -  - :doc:`../pcb-layout-design`
            - 章节 :ref:`sdio-layout`：更新 SDIO 版图设计规范
            - 章节 :ref:`crystal-layout`：更新晶振版图设计规范
   * - 2025-3-31
     - v1.0
     - 首次发布《{IDF_TARGET_NAME} 硬件设计指南》 HTML 版本。
