.. _ADC Functions:

ADC 功能详见下表。

.. list-table:: ADC 功能
   :name: tab-adc-gpio
   :header-rows: 1
   :widths: 10 10 10

   * - 管脚序号
     - GPIO 管脚
     - ADC 功能
   * - 6
     - GPIO0
     - ADC1_CH0
   * - 7
     - GPIO1
     - ADC1_CH1
   * - 8
     - GPIO2
     - ADC1_CH2
   * - 9
     - GPIO3
     - ADC1_CH3
   * - 10
     - GPIO4
     - ADC1_CH4
   * - 11
     - GPIO5
     - ADC1_CH5
   * - 12
     - GPIO6
     - ADC1_CH6
