#!/usr/bin/env python3
"""Generate per-target module and development-board RST includes from wiki YAML.

Reads product_catalog.yaml and document_owner.yaml from doc-team-wiki and writes
docs/{en,zh_CN}/{slug}/{slug}-modules.inc and {slug}-devkits.inc.
"""

from __future__ import annotations

import argparse
import re
import subprocess
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

import yaml

SERIES_TO_SLUG = {
    "ESP32": "esp32",
    "ESP32-S2": "esp32s2",
    "ESP32-S3": "esp32s3",
    "ESP32-S31": "esp32s31",
    "ESP32-C2": "esp32c2",
    "ESP32-C3": "esp32c3",
    "ESP32-C5": "esp32c5",
    "ESP32-C6": "esp32c6",
    "ESP32-C61": "esp32c61",
    "ESP32-H2": "esp32h2",
    "ESP32-P4": "esp32p4",
}

SLUG_TO_SERIES = {slug: series for series, slug in SERIES_TO_SLUG.items()}
KIND_LABEL = {
    "modules": "module",
    "devkits": "development board",
}
_LIST_ITEM_RE = re.compile(
    r"^- (?:`(?P<linked_name>.+?) <(?P<url>[^>]+)>`__|(?P<plain_name>.+))\s*$"
)

ALLOWED_STATUSES = frozenset({"SAMPLE", "MASS_PRODUCTION"})
MODULE_TYPES = frozenset({"Modules", "ESP Module Series"})
DEVKIT_TYPES = frozenset({"DevKits", "ESP DevKits"})

GENERATED_COMMENT = (
    "..\n   Auto-generated by tools/generate_product_lists.py. Do not edit.\n"
)

HEADINGS = {
    "en": {
        "modules": (
            "{IDF_TARGET_NAME} Modules\n"
            "------------------------------"
        ),
        "devkits": (
            "{IDF_TARGET_NAME} Development Boards\n"
            "--------------------------------------------"
        ),
    },
    "zh_CN": {
        "modules": (
            "{IDF_TARGET_NAME} 系列模组\n"
            "------------------------------"
        ),
        "devkits": (
            "{IDF_TARGET_NAME} 系列开发板\n"
            "--------------------------------"
        ),
    },
}

SECTION_INTROS = {
    "en": {
        "modules": (
            "This section lists only sample and mass-production {IDF_TARGET_NAME} modules. "
            "For the complete list, see the "
            "`Modules <https://www.espressif.com/en/products/modules#{IDF_TARGET_NAME}>`__ "
            "page on the Espressif website."
        ),
        "devkits": (
            "This section lists only sample and mass-production {IDF_TARGET_NAME} development boards. "
            "For the complete list, see the "
            "`Development Boards <https://www.espressif.com/en/products/devkits#{IDF_TARGET_NAME}>`__ "
            "page on the Espressif website."
        ),
    },
    "zh_CN": {
        "modules": (
            "本节仅列出样品和量产状态的 {IDF_TARGET_NAME} 系列模组。"
            "完整列表请前往乐鑫官网 "
            "`模组页面 <https://www.espressif.com/zh-hans/products/modules#{IDF_TARGET_NAME}>`__。"
        ),
        "devkits": (
            "本节仅列出样品和量产状态的 {IDF_TARGET_NAME} 系列开发板。"
            "完整列表请前往乐鑫官网 "
            "`开发板页面 <https://www.espressif.com/zh-hans/products/devkits#{IDF_TARGET_NAME}>`__。"
        ),
    },
}

SAMPLE_SUFFIX = {
    "en": " (sample)",
    "zh_CN": "（样品）",
}

MODULES_LABEL = ".. _hardware-development-modules:\n"

_NAME_IN_TITLE_RE_CACHE: Dict[str, re.Pattern[str]] = {}
_VERSION_RE = re.compile(r"[vV](\d+(?:\.\d+)*)")
_CN_URL_MARKERS = ("_cn.", "/zh_cn/", "/zh-hans/", "/zh_cn/")
_EN_URL_MARKERS = ("_en.", "/en/")
_CHIP_DATASHEET_HINTS = (
    "系列芯片技术规格书",
    "系列技术规格书",
    "Series Datasheet",
    "Chip Datasheet",
)
_EXCLUDE_BOARD_TITLE = (
    "ESP-AT",
    "ESP-IDF",
    "Reference Design",
    "参考设计",
    "AT 指令",
    "AT Instruction",
    "SDK User Guide",
    "SDK 用户指南",
)


def _product_name_pattern(name: str) -> re.Pattern[str]:
    cached = _NAME_IN_TITLE_RE_CACHE.get(name)
    if cached is not None:
        return cached
    pattern = re.compile(
        r"(?<![A-Za-z0-9-])" + re.escape(name) + r"(?![A-Za-z0-9-])"
    )
    _NAME_IN_TITLE_RE_CACHE[name] = pattern
    return pattern


def name_in_title(name: str, title: str) -> bool:
    """True when *name* appears as a whole product token in *title*."""
    if not name or not title:
        return False
    return _product_name_pattern(name).search(title) is not None


def document_language(doc: Dict[str, Any]) -> Optional[str]:
    title = str(doc.get("title") or "")
    url = str(doc.get("target_location") or "").lower()
    if any(marker in url for marker in _CN_URL_MARKERS):
        return "zh_CN"
    if any(marker in url for marker in _EN_URL_MARKERS):
        return "en"
    if any(
        token in title
        for token in ("技术规格书", "用户指南", "入门指南", "用户手册", "参考设计")
    ):
        return "zh_CN"
    if any(
        token in title
        for token in (
            "Datasheet",
            "User Guide",
            "Getting Started",
            "User Manual",
            "Reference Design",
            "Hardware Reference",
        )
    ):
        return "en"
    return None


def is_module_datasheet_title(title: str) -> bool:
    if "Datasheet" not in title and "技术规格书" not in title:
        return False
    if any(hint in title for hint in _CHIP_DATASHEET_HINTS):
        return False
    if "芯片技术规格书" in title and "模组" not in title:
        return False
    return True


def is_board_doc_title(title: str) -> bool:
    if any(token in title for token in _EXCLUDE_BOARD_TITLE):
        return False
    return bool(
        "User Guide" in title
        or "用户指南" in title
        or "Getting Started" in title
        or "入门指南" in title
        or "Hardware Reference" in title
        or "User Manual" in title
        or "用户手册" in title
    )


def board_doc_rank(title: str) -> int:
    if "User Guide" in title or "用户指南" in title:
        return 4
    if "Getting Started" in title or "入门指南" in title:
        return 3
    if "Hardware Reference" in title:
        return 2
    if "User Manual" in title or "用户手册" in title:
        return 1
    return 0


def title_version(title: str) -> Tuple[int, ...]:
    match = _VERSION_RE.search(title)
    if not match:
        return ()
    return tuple(int(part) for part in match.group(1).split("."))


def revision_sort_key(value: Any) -> str:
    return str(value or "")


def pick_best_document(docs: Sequence[Dict[str, Any]], kind: str) -> Optional[Dict[str, Any]]:
    if not docs:
        return None
    if kind == "modules":
        ranked = sorted(
            docs,
            key=lambda doc: revision_sort_key(doc.get("revision_date")),
            reverse=True,
        )
        return ranked[0]
    ranked = sorted(
        docs,
        key=lambda doc: (
            board_doc_rank(str(doc.get("title") or "")),
            title_version(str(doc.get("title") or "")),
            revision_sort_key(doc.get("revision_date")),
        ),
        reverse=True,
    )
    return ranked[0]


def load_yaml(path: Path) -> Any:
    with path.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def iter_hardware_products(catalog: Dict[str, Any]) -> Iterable[Dict[str, Any]]:
    products = catalog.get("products") or catalog
    hardware = products.get("hardware") or {}
    for product_id, fields in hardware.items():
        if product_id == "_meta" or not isinstance(fields, dict):
            continue
        item = dict(fields)
        item["product_id"] = str(product_id)
        yield item


def filter_listed_products(
    catalog: Dict[str, Any],
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    included: List[Dict[str, Any]] = []
    skipped_multi: List[Dict[str, Any]] = []
    for product in iter_hardware_products(catalog):
        product_type = str(product.get("product_type") or "").strip()
        if product_type in MODULE_TYPES:
            kind = "modules"
        elif product_type in DEVKIT_TYPES:
            kind = "devkits"
        else:
            continue
        status = str(product.get("marketing_status") or "").strip().upper()
        if status not in ALLOWED_STATUSES:
            continue
        series_list = [
            str(item).strip()
            for item in (product.get("soc_series_bases") or [])
            if str(item).strip()
        ]
        if len(series_list) != 1:
            skipped_multi.append(product)
            continue
        series = series_list[0]
        slug = SERIES_TO_SLUG.get(series)
        if slug is None:
            continue
        item = dict(product)
        item["kind"] = kind
        item["series"] = series
        item["slug"] = slug
        item["marketing_status"] = status
        included.append(item)
    included.sort(key=lambda item: (item["slug"], item["kind"], item.get("product_name") or ""))
    return included, skipped_multi


def load_documents(documents_yaml: Dict[str, Any]) -> List[Dict[str, Any]]:
    root = documents_yaml.get("documents") or documents_yaml
    data = root.get("data") if isinstance(root, dict) else None
    if isinstance(data, list):
        return [item for item in data if isinstance(item, dict)]
    if isinstance(root, list):
        return [item for item in root if isinstance(item, dict)]
    return []


def match_documents(
    product: Dict[str, Any],
    documents: Sequence[Dict[str, Any]],
    language: str,
) -> List[Dict[str, Any]]:
    name = str(product.get("product_name") or "").strip()
    kind = product["kind"]
    hits: List[Dict[str, Any]] = []
    for doc in documents:
        if document_language(doc) != language:
            continue
        title = str(doc.get("title") or "")
        if not name_in_title(name, title):
            continue
        if kind == "modules" and not is_module_datasheet_title(title):
            continue
        if kind == "devkits" and not is_board_doc_title(title):
            continue
        hits.append(doc)
    return hits


def display_name(product: Dict[str, Any], language: str) -> str:
    name = str(product.get("product_name") or "").strip()
    if product.get("marketing_status") == "SAMPLE":
        return name + SAMPLE_SUFFIX[language]
    return name


def html_to_pdf_url(url: Optional[str]) -> Optional[str]:
    """Use the PDF datasheet when the catalog points at the HTML copy."""
    if url and url.endswith(".html"):
        return url[:-5] + ".pdf"
    return url


def rst_list_item(name: str, url: Optional[str]) -> str:
    if url:
        return f"- `{name} <{url}>`__"
    return f"- {name}"


def render_include(
    language: str,
    kind: str,
    products: Sequence[Tuple[Dict[str, Any], Optional[str]]],
) -> str:
    lines = [GENERATED_COMMENT]
    if not products:
        return "\n".join(lines) + "\n"
    if kind == "modules":
        lines.append(MODULES_LABEL)
    lines.append(HEADINGS[language][kind])
    lines.append("")
    lines.append(SECTION_INTROS[language][kind])
    lines.append("")
    for product, url in products:
        if kind == "modules":
            url = html_to_pdf_url(url)
        lines.append(rst_list_item(display_name(product, language), url))
    lines.append("")
    return "\n".join(lines)


def include_path(docs_root: Path, language: str, slug: str, kind: str) -> Path:
    filename = f"{slug}-{kind}.inc"
    return docs_root / language / slug / filename


def strip_sample_suffix(name: str) -> str:
    text = name.strip()
    for suffix in SAMPLE_SUFFIX.values():
        if text.endswith(suffix):
            return text[: -len(suffix)]
    return text


def parse_include_items(text: str) -> Dict[str, Tuple[str, Optional[str]]]:
    """Map base product name to (display name, URL) from a generated include."""
    items: Dict[str, Tuple[str, Optional[str]]] = {}
    for line in text.splitlines():
        match = _LIST_ITEM_RE.match(line)
        if not match:
            continue
        display = (match.group("linked_name") or match.group("plain_name") or "").strip()
        if not display:
            continue
        items[strip_sample_suffix(display)] = (display, match.group("url"))
    return items


def baseline_include_text(docs_root: Path, language: str, slug: str, kind: str) -> str:
    path = include_path(docs_root, language, slug, kind)
    repo_root = docs_root.resolve().parent
    try:
        rel_path = path.resolve().relative_to(repo_root)
        text = git_head_text(repo_root, rel_path)
        if text is not None:
            return text
    except ValueError:
        pass
    if path.is_file():
        return path.read_text(encoding="utf-8")
    return ""


def grouped_items(
    grouped: Dict[Tuple[str, str, str], List[Tuple[Dict[str, Any], Optional[str]]]],
    language: str,
    slug: str,
    kind: str,
) -> Dict[str, Tuple[str, Optional[str]]]:
    items: Dict[str, Tuple[str, Optional[str]]] = {}
    for product, url in grouped.get((language, slug, kind), []):
        name = str(product.get("product_name") or "").strip()
        if not name:
            continue
        items[name] = (display_name(product, language), url or None)
    return items


def diff_product_lists(
    docs_root: Path,
    grouped: Dict[Tuple[str, str, str], List[Tuple[Dict[str, Any], Optional[str]]]],
) -> List[Dict[str, Any]]:
    """Per-series added / removed products and documentation-link updates."""
    changes: List[Dict[str, Any]] = []
    for series, slug in SERIES_TO_SLUG.items():
        added: List[str] = []
        removed: List[str] = []
        updated: List[str] = []
        for kind in ("modules", "devkits"):
            label = KIND_LABEL[kind]
            old_en = parse_include_items(baseline_include_text(docs_root, "en", slug, kind))
            old_cn = parse_include_items(baseline_include_text(docs_root, "zh_CN", slug, kind))
            new_en = grouped_items(grouped, "en", slug, kind)
            new_cn = grouped_items(grouped, "zh_CN", slug, kind)
            old_names = set(old_en) | set(old_cn)
            new_names = set(new_en) | set(new_cn)
            for name in sorted(new_names - old_names):
                display = (new_en.get(name) or new_cn.get(name) or (name, None))[0]
                added.append(f"{display} ({label})")
            for name in sorted(old_names - new_names):
                display = (old_en.get(name) or old_cn.get(name) or (name, None))[0]
                removed.append(f"{display} ({label})")
            for name in sorted(old_names & new_names):
                old_en_url = (old_en.get(name) or (name, None))[1]
                old_cn_url = (old_cn.get(name) or (name, None))[1]
                new_en_url = (new_en.get(name) or (name, None))[1]
                new_cn_url = (new_cn.get(name) or (name, None))[1]
                if old_en_url != new_en_url or old_cn_url != new_cn_url:
                    display = (new_en.get(name) or new_cn.get(name) or (name, None))[0]
                    updated.append(f"{display} ({label})")
        if added or removed or updated:
            changes.append(
                {
                    "series": series,
                    "added": added,
                    "removed": removed,
                    "updated_links": updated,
                }
            )
    return changes


def build_lists(
    catalog: Dict[str, Any],
    documents_yaml: Dict[str, Any],
) -> Tuple[Dict[Tuple[str, str, str], List[Tuple[Dict[str, Any], Optional[str]]]], Dict[str, Any]]:
    products, skipped_multi = filter_listed_products(catalog)
    documents = load_documents(documents_yaml)
    grouped: Dict[Tuple[str, str, str], List[Tuple[Dict[str, Any], Optional[str]]]] = defaultdict(list)
    missing: List[Dict[str, Any]] = []
    for product in products:
        for language in ("en", "zh_CN"):
            hits = match_documents(product, documents, language)
            chosen = pick_best_document(hits, product["kind"])
            url = str(chosen.get("target_location") or "").strip() if chosen else ""
            if product["kind"] == "modules":
                url = html_to_pdf_url(url) or ""
            if not url:
                missing.append(
                    {
                        "language": language,
                        "kind": product["kind"],
                        "series": product["series"],
                        "product_name": product.get("product_name"),
                        "product_id": product.get("product_id"),
                    }
                )
            grouped[(language, product["slug"], product["kind"])].append(
                (product, url or None)
            )
    report = {
        "products": products,
        "skipped_multi": skipped_multi,
        "missing": missing,
    }
    return grouped, report


def write_includes(
    docs_root: Path,
    grouped: Dict[Tuple[str, str, str], List[Tuple[Dict[str, Any], Optional[str]]]],
) -> List[Path]:
    written: List[Path] = []
    for language in ("en", "zh_CN"):
        for slug in SERIES_TO_SLUG.values():
            for kind in ("modules", "devkits"):
                products = grouped.get((language, slug, kind), [])
                path = include_path(docs_root, language, slug, kind)
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(render_include(language, kind, products), encoding="utf-8")
                written.append(path)
    return written


def git_head_text(repo_root: Path, rel_path: Path) -> Optional[str]:
    proc = subprocess.run(
        ["git", "-C", str(repo_root), "show", f"HEAD:{rel_path.as_posix()}"],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        return None
    return proc.stdout


def changed_slugs(
    docs_root: Path,
    grouped: Dict[Tuple[str, str, str], List[Tuple[Dict[str, Any], Optional[str]]]],
) -> Set[str]:
    repo_root = docs_root.resolve().parent
    changed: Set[str] = set()
    for language in ("en", "zh_CN"):
        for slug in SERIES_TO_SLUG.values():
            for kind in ("modules", "devkits"):
                expected = render_include(
                    language, kind, grouped.get((language, slug, kind), [])
                )
                path = include_path(docs_root, language, slug, kind)
                try:
                    rel_path = path.resolve().relative_to(repo_root)
                    baseline = git_head_text(repo_root, rel_path)
                except ValueError:
                    baseline = path.read_text(encoding="utf-8") if path.is_file() else ""
                if baseline is None:
                    baseline = ""
                if baseline != expected:
                    changed.add(slug)
    return changed


def format_change_summary(changes: List[Dict[str, Any]]) -> str:
    if not changes:
        return "No product additions, removals, or documentation-link updates.\n"
    lines: List[str] = []
    for item in changes:
        lines.append(f"### {item['series']}")
        lines.append("")
        if item["added"]:
            lines.append("Added")
            for entry in item["added"]:
                lines.append(f"- {entry}")
            lines.append("")
        if item["removed"]:
            lines.append("Removed")
            for entry in item["removed"]:
                lines.append(f"- {entry}")
            lines.append("")
        if item["updated_links"]:
            lines.append("Updated documentation links")
            for entry in item["updated_links"]:
                lines.append(f"- {entry}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def format_summary(report: Dict[str, Any]) -> str:
    return format_change_summary(report.get("changes") or [])


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--catalog",
        type=Path,
        required=True,
        help="Path to doc-team-wiki product_catalog.yaml",
    )
    parser.add_argument(
        "--documents",
        type=Path,
        required=True,
        help="Path to doc-team-wiki document_owner.yaml",
    )
    parser.add_argument(
        "--docs-root",
        type=Path,
        default=Path("docs"),
        help="HDG docs/ directory",
    )
    parser.add_argument("--summary-output", type=Path, default=None)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated files would differ from what is on disk",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    catalog = load_yaml(args.catalog)
    documents_yaml = load_yaml(args.documents)
    grouped, report = build_lists(catalog, documents_yaml)
    slugs = changed_slugs(args.docs_root, grouped)
    changes = diff_product_lists(args.docs_root, grouped)
    report["changes"] = changes
    summary = format_change_summary(changes)
    print(summary)
    if args.check:
        dirty = bool(slugs)
        for slug in sorted(slugs):
            print(f"Would update product lists for {slug}")
        if dirty:
            return 1
        print("Generated product lists are up to date.")
        return 0
    write_includes(args.docs_root, grouped)
    if args.summary_output:
        args.summary_output.write_text(summary, encoding="utf-8")
        print(f"Wrote {args.summary_output}")
    print(f"Wrote includes under {args.docs_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
