.. list-table:: Touch Sensor Functions
   :name: tab-touch-gpio
   :header-rows: 1
   :widths: 50 50
   :align: center

   * - GPIO Pin Name
     - Touch Sensor Function
   * - GPIO2
     - TOUCH_CHANNEL1
   * - GPIO3
     - TOUCH_CHANNEL2
   * - GPIO4
     - TOUCH_CHANNEL3
   * - GPIO5
     - TOUCH_CHANNEL4
   * - GPIO6
     - TOUCH_CHANNEL5
   * - GPIO7
     - TOUCH_CHANNEL6
   * - GPIO8
     - TOUCH_CHANNEL7
   * - GPIO9
     - TOUCH_CHANNEL8
   * - GPIO10
     - TOUCH_CHANNEL9
   * - GPIO11
     - TOUCH_CHANNEL10
   * - GPIO12
     - TOUCH_CHANNEL11
   * - GPIO13
     - TOUCH_CHANNEL12
   * - GPIO14
     - TOUCH_CHANNEL13
   * - GPIO15
     - TOUCH_CHANNEL14
