When using the ADC function, place a 0.1 μF capacitor to ground near the pin to improve accuracy.

.. list-table::
    :header-rows: 1
    :widths: 15 10

    * - ADC Channel Signal
      - Pin Name

    * - ADC1_CHANNEL0
      - GPIO16
    * - ADC1_CHANNEL1
      - GPIO17
    * - ADC1_CHANNEL2
      - GPIO18
    * - ADC1_CHANNEL3
      - GPIO19
    * - ADC1_CHANNEL4
      - GPIO20
    * - ADC1_CHANNEL5
      - GPIO21
    * - ADC1_CHANNEL6
      - GPIO22
    * - ADC1_CHANNEL7
      - GPIO23
    * - ADC2_CHANNEL0
      - GPIO49
    * - ADC2_CHANNEL1
      - GPIO50
    * - ADC2_CHANNEL2
      - GPIO51
    * - ADC2_CHANNEL3
      - GPIO52
    * - ADC2_CHANNEL4
      - GPIO53
    * - ADC2_CHANNEL5
      - GPIO54
